version: '3'

services:
  supreme_umbrella_nginx:
    build:
      context: .
      dockerfile: nginx/dockerfile
    volumes:
      - ../:/var/www/supreme_umbrella_symfony/
    ports:
      - "8001:8001"
      - "8002:8002"
    networks:
      - symfony
    links:
      - supreme_umbrella_php
    depends_on:
      - supreme_umbrella_php

  supreme_umbrella_php:
    build:
      context: .
      dockerfile: php/dockerfile
    environment:
      APP_ENV: dev
    volumes:
      - ../:/var/www/supreme_umbrella_symfony/
    depends_on:
      - supreme_umbrella_db
    networks:
      - symfony

  supreme_umbrella_db:
    image: mysql
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    ports:
      - "3308:3308"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent" ]
      interval: 2s
      timeout: 10s
      retries: 10
    networks:
      - symfony

networks:
  symfony:
