<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWZ56Mck\SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWZ56Mck/SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWZ56Mck.legacy');

    return;
}

if (!\class_exists(SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWZ56Mck\SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, false);
}

return new \ContainerWZ56Mck\SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer([
    'container.build_hash' => 'WZ56Mck',
    'container.build_id' => 'cb2c4285',
    'container.build_time' => 1671607655,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWZ56Mck');
