<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCYhk529\SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCYhk529/SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCYhk529.legacy');

    return;
}

if (!\class_exists(SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCYhk529\SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, false);
}

return new \ContainerCYhk529\SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer([
    'container.build_hash' => 'CYhk529',
    'container.build_id' => '5e8712ad',
    'container.build_time' => 1671609095,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCYhk529');
