<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTD1bYgx\SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTD1bYgx/SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTD1bYgx.legacy');

    return;
}

if (!\class_exists(SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTD1bYgx\SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, false);
}

return new \ContainerTD1bYgx\SupremeUmbrella_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer([
    'container.build_hash' => 'TD1bYgx',
    'container.build_id' => '73062b7b',
    'container.build_time' => 1671354340,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTD1bYgx');
